/* ACCORDION */
jQuery(document).ready(function(){"use strict";jQuery(".dvteam_input_title h3").click(function(){if(jQuery(this).parent().next(".dvteam_all_options").css("display")==="none"){jQuery(this).removeClass("inactive");jQuery(this).addClass("active")}else{jQuery(this).removeClass("active");jQuery(this).addClass("inactive")}jQuery(this).parent().next(".dvteam_all_options").slideToggle(200);return false})});

/* INPUT NUMBER VALIDATION */
function validate(e){var t=e.which?e.which:event.keyCode;if(t>31&&(t<45||t>57)){return false}return true}

/* COLORPICKER */
jQuery(document).ready(function(e){e(".dvteam-color").wpColorPicker()});

/* SELECT BOX */
jQuery(function(){jQuery('.dvteam-select').selectric();});

/* RGBA COLORPICKER */
(function(e,t,n,r){"use strict";if(typeof Color.fn.toString!==r){Color.fn.toString=function(){if(this._alpha<1){return this.toCSS("rgba",this._alpha).replace(/\s+/g,"")}var e=parseInt(this._color,10).toString(16);if(this.error){return""}if(e.length<6){for(var t=6-e.length-1;t>=0;t--){e="0"+e}}return"#"+e}}e.cs_ParseColorValue=function(e){var t=e.replace(/\s+/g,""),n=t.indexOf("rgba")!==-1?parseFloat(t.replace(/^.*,(.+)\)/,"$1")*100):100,r=n<100?true:false;return{value:t,alpha:n,rgba:r}};e.fn.cs_wpColorPicker=function(){return this.each(function(){var t=e(this);if(t.data("rgba")!==false){var n=e.cs_ParseColorValue(t.val());t.wpColorPicker({change:function(e,n){t.closest(".wp-picker-container").find(".dvteam-alpha-slider-offset").css("background-color",n.color.toString());t.trigger("keyup")},create:function(r,i){var s=t.data("a8cIris"),o=t.closest(".wp-picker-container"),u=e('<div class="dvteam-alpha-wrap">'+'<div class="dvteam-alpha-slider"></div>'+'<div class="dvteam-alpha-slider-offset"></div>'+'<div class="dvteam-alpha-text"></div>'+"</div>").appendTo(o.find(".wp-picker-holder")),a=u.find(".dvteam-alpha-slider"),f=u.find(".dvteam-alpha-text"),l=u.find(".dvteam-alpha-slider-offset");a.slider({slide:function(e,n){var r=parseFloat(n.value/100);s._color._alpha=r;t.wpColorPicker("color",s._color.toString());f.text(r<1?r:"")},create:function(){var r=parseFloat(n.alpha/100),i=r<1?r:"";f.text(i);l.css("background-color",n.value);o.on("click",".wp-picker-clear",function(){s._color._alpha=1;f.text("");a.slider("option","value",100).trigger("slide")});o.on("click",".wp-picker-default",function(){var n=e.cs_ParseColorValue(t.data("default-color")),r=parseFloat(n.alpha/100),i=r<1?r:"";s._color._alpha=r;f.text(i);a.slider("option","value",n.alpha).trigger("slide")});o.on("click",".wp-color-result",function(){u.toggle()});e("body").on("click.wpcolorpicker",function(){u.hide()})},value:n.alpha,step:1,min:1,max:100})}})}else{t.wpColorPicker({change:function(){t.trigger("keyup")}})}})};e(n).ready(function(){e(".dvteam-wp-color-picker").cs_wpColorPicker()})})(jQuery,window,document)